blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/your-username/pia-mcp-local/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/your-username/pia-mcp-local/blob/main/README.md
    about: Check out the project documentation
